export const FREE_SHIPPING_THRESHOLD = 10_000_000;
export const STANDARD_SHIPPING_FEE = 50_000;

export const DEFAULT_LOW_STOCK_THRESHOLD = 5;
export const DEFAULT_TOP_PRODUCTS_LIMIT = 5;
export const DEFAULT_RECENT_ORDERS_LIMIT = 10;
export const DEFAULT_DAILY_REVENUE_DAYS = 7;
export const DEFAULT_RELATED_PRODUCTS_LIMIT = 4;
